name: ServerStatus-Spigot
version: 2.0.0
main: xyz.fcidd.serverstatus.ServerStatus
api-version: 1.16
authors:
  - "Maple_Dust"
  - "Harvey_Husky"
commands:
  bgServerStatus:
    description: 发送自定义消息到前端
    usage: /<command>
permissions: 
  serverstatus.command.serverstatus:
    description: bgServerStatus命令的主权限，给玩家无用
    default: false
  serverstatus.command.serverstatus.reload: 
    description: bgServerStatus close子命令权限
    default: false
    children:
      serverstatus.command.serverstatus: true
  serverstatus.command.serverstatus.help: 
    description: bgServerStatus close子命令权限
    default: false
    children:
      serverstatus.command.serverstatus: true
  serverstatus.command.serverstatus.setport: 
    description: bgServerStatus close子命令权限
    default: false
    children:
      serverstatus.command.serverstatus: true
  serverstatus.command.serverstatus.sethost: 
    description: bgServerStatus close子命令权限
    default: false
    children:
      serverstatus.command.serverstatus: true
  serverstatus.command.serverstatus.message: 
    description: bgServerStatus message子命令权限
    default: false
    children:
      serverstatus.command.serverstatus: true
  serverstatus.command.admin: 
    description: 所有命令的主权限
    default: false
    children:
      serverstatus.command.serverstatus.message: true
      serverstatus.command.serverstatus.sethost: true
      serverstatus.command.serverstatus.setport: true
      serverstatus.command.serverstatus.help: true
      serverstatus.command.serverstatus.reload: true